#! /bin/bash

{
	set -eu
	
	# must be root to control docker
	if [ "$USER" != "root" ]
	then
		sudo "$0"
		exit
	fi
	
	# new single stage build
	sudo DOCKER_BUILDKIT=1 docker build --tag macemu-build docker
	
	# for debugging:
	# sudo docker run --rm -it macemu-build /bin/bash
	
	echo -n "Extracting files ..."
	sudo docker run --rm \
		-v "$(realpath ./output):/externalOutput" \
		macemu-build
		
	echo
	
	# convenience: chown the output directory to the sudo caller
	if [ "${SUDO_USER:-}" != "" ]
	then
		chown "$SUDO_USER" -R output
	fi
	
	echo -e "\n\nBUILD COMPLETE\nOutput files in directory \"output\"\n\n"
	sleep 1

	exit
}
