#! /bin/bash
{
	set -eu

	# delete old output
	rm -rf /output/*
	mkdir /output/macemuAppImages
	mkdir /output/installFiles

	# pack BasiliskII & BasiliskIIGUI
	cd /usr/local/src/macemu/BasiliskII/src/Unix

	cp /build/BasiliskII.desktop ./AppDir/

	gm convert /usr/local/src/macemu/BasiliskII/src/Windows/BasiliskII.ico ./BasiliskII.png
	gm convert /usr/local/src/macemu/BasiliskII/src/Windows/BasiliskIIGUI.ico ./BasiliskIIGUI.png

	cp ./BasiliskII.png /output/installFiles/
	cp ./BasiliskIIGUI.png /output/installFiles/
	cp /build/BasiliskII.desktop /output/installFiles/
	cp /build/BasiliskIIGUI.desktop /output/installFiles/

	(
	linuxdeploy \
		--appdir AppDir \
		--executable ./BasiliskII \
		--library /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 \
		--library /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 \
		--desktop-file=/build/BasiliskII.desktop \
		--icon-file=BasiliskII.png \
		--output appimage 2>&1 | tee /tmp/linuxdeploy-BasiliskII

	# add to output
	cp ./*.AppImage /output/macemuAppImages/
	
	) &
	job1Pid=$!
	
	# pack SheepShaver & SheepShaverGUI
	cd /usr/local/src/macemu/SheepShaver/src/Unix

	cp /build/SheepShaver.desktop ./AppDir/

	gm convert /usr/local/src/macemu/SheepShaver/src/Windows/SheepShaver.ico ./SheepShaver.png
	gm convert /usr/local/src/macemu/SheepShaver/src/Windows/SheepShaverGUI.ico ./SheepShaverGUI.png
	
	cp ./SheepShaver.png /output/installFiles/
	cp ./SheepShaverGUI.png /output/installFiles/
	cp /build/SheepShaver.desktop /output/installFiles/
	cp /build/SheepShaverGUI.desktop /output/installFiles/
	
	(
	linuxdeploy \
		--appdir AppDir \
		--executable ./SheepShaver \
		--library /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 \
		--library /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 \
		--desktop-file=/build/SheepShaver.desktop \
		--icon-file=SheepShaver.png \
		--output appimage 2>&1 | tee /tmp/linuxdeploy-SheepShaver
	
	# add to output
	cp ./*.AppImage /output/macemuAppImages/
	) &
	job2Pid=$!
	
	if ! wait $job1Pid
	then
		wait $job2Pid || echo
		echo
		echo
		echo "linuxdeploy BasiliskII failed, repeating output on stderr"
		sleep 1
		cat /tmp/linuxdeploy-BasiliskII >&2
		exit 2
	fi
	if ! wait $job2Pid
	then
		echo
		echo
		echo "linuxdeploy SheepShaver failed, repeating output on stderr"
		sleep 1
		cat /tmp/linuxdeploy-SheepShaver >&2
		exit 3
	fi
	
	# rename output files to be more readable
	cd /output/macemuAppImages
	mv BasiliskII-*.AppImage BasiliskII.AppImage
	mv SheepShaver-*.AppImage SheepShaver.AppImage

	# add helpers
	cp /build/helpers/* /output/
	

	exit
}
