name: Build bot

on:
  issue_comment:
    types:
    - created
jobs:
  gotcha:
    if: |
      contains(github.event.comment.body, 'Hey build bot, please build macemu-amd64-basilisk2.AppImage!') ||
      contains(github.event.comment.body, 'Hey build bot, please build macemu-i386-basilisk2.AppImage!') ||
      contains(github.event.comment.body, 'Hey build bot, please build macemu-amd64-sheepshaver.AppImage!') ||
      contains(github.event.comment.body, 'Hey build bot, please build macemu-i386-sheepshaver.AppImage!') ||
      contains(github.event.comment.body, 'Hey build bot, please build nothing!')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            const {owner, repo} = context.issue
            github.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "rocket",
            });
  basilisk2_amd64:
    if: contains(github.event.comment.body, 'Hey build bot, please build macemu-amd64-basilisk2.AppImage!')
    name: "BasiliskII amd64"
    uses: ./.github/workflows/compile-platform.yml
    with:
      platform: amd64
      target_stage: basilisk2
  basilisk2_i386:
    if: contains(github.event.comment.body, 'Hey build bot, please build macemu-i386-basilisk2.AppImage!')
    name: "BasiliskII i386"
    uses: ./.github/workflows/compile-platform.yml
    with:
      platform: i386
      target_stage: basilisk2
  sheepshaver_amd64:
    if: contains(github.event.comment.body, 'Hey build bot, please build macemu-amd64-sheepshaver.AppImage!')
    name: "SheepShaver amd64"
    uses: ./.github/workflows/compile-platform.yml
    with:
      platform: amd64
      target_stage: sheepshaver
  sheepshaver_i386:
    if: contains(github.event.comment.body, 'Hey build bot, please build macemu-i386-sheepshaver.AppImage!')
    name: "SheepShaver i386"
    uses: ./.github/workflows/compile-platform.yml
    with:
      platform: i386
      target_stage: sheepshaver
  reply:
    if: always()
    needs: [gotcha, basilisk2_amd64, basilisk2_i386, sheepshaver_amd64, sheepshaver_i386]
    runs-on: ubuntu-latest
    steps:
    - name: Message success
      if: ${{ success() }}
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "Build succeeded! ✅\n\nDownload from the [continuous release](https://github.com/Korkman/macemu-appimage-builder/releases/tag/continuous)",
          });
          github.reactions.createForIssueComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: context.payload.comment.id,
            content: "+1",
          });
    - name: Message failure
      if: ${{ failure() }}
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "Build failed! ❌\n\nIf multiple builds were requested, visit the [continuous release](https://github.com/Korkman/macemu-appimage-builder/releases/tag/continuous) to see which succeeded.",
          });
          github.reactions.createForIssueComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: context.payload.comment.id,
            content: "-1",
          });          
