name: Build all
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # trigger workflows
  basilisk2_x86_64:
    name: "BasiliskII x86_64"
    uses: ./.github/workflows/compile-platform.yml
    with:
      platform: x86_64
      target_stage: basilisk2
  basilisk2_i386:
    name: "BasiliskII i386"
    uses: ./.github/workflows/compile-platform.yml
    with:
      platform: i386
      target_stage: basilisk2
  sheepshaver_x86_64:
    name: "SheepShaver x86_64"
    uses: ./.github/workflows/compile-platform.yml
    with:
      platform: x86_64
      target_stage: sheepshaver
  sheepshaver_i386:
    name: "SheepShaver i386"
    uses: ./.github/workflows/compile-platform.yml
    with:
      platform: i386
      target_stage: sheepshaver
