name: Compile and release
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # run this every month on the second monday at 7:20'o clock UTC
    #- cron:  '20 7 8-14 * 1'
    # run this every friday at 13:37 UTC
    - cron:  '37 13 * * 5'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # trigger workflows
  compile_and_release:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Compile
        run: sudo ./compile
      
      - name: List files for the log
        run: ls -al output/
      
      - name: Make nice directory name
        run: mv output macemu
      
      - name: Create tar.gz
        run: tar -czvf build-result.tar.gz macemu
      
      # save artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: build-result
          path: build-result.tar.gz
      
      # copy & paste release.yml from this point
      
      - name: List files for the log
        run: ls -al
      
      - name: version
        run: echo "::set-output name=version::$(date +%Y-%m-%d.%s)"
        id: version
        
      - name: Rename release
        run: "mv build-result.tar.gz build-${{ steps.version.outputs.version }}.tar.gz"
      
      # create a release
      - uses: "ncipollo/release-action@v1"
        with:
          tag: "${{ steps.version.outputs.version }}"
          #token: "${{ secrets.GITHUB_TOKEN }}"
          name: "${{ steps.version.outputs.version }}"
          prerelease: false
          draft: false
          #generateReleaseNotes: false
          bodyFile: .github/AUTORELEASE.md
          allowUpdates: true
          artifacts: "build-${{ steps.version.outputs.version }}.tar.gz"
          artifactContentType: application/gzip
