name: Compile platform

# Controls when the workflow will run
on:
  workflow_call: # Allow reuse of this workflow
    inputs:
      platform:
        description: "Target platform, e.g. amd64 or i386"
        required: true
        default: "amd64"
        type: string
      target_stage:
        description: "Target stage, e.g. combined or basilisk2 or sheepshaver"
        required: true
        default: "combined"
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Compile
        run: sudo ./compile ${{ inputs.platform }} ${{ inputs.target_stage }}
      
      - name: Make nice directory name
        run: mv output macemu
      
      - name: Create tar.gz
        run: tar -czvf macemu-${{ inputs.platform }}-${{ inputs.target_stage }}.tar.gz macemu
      
      # save artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: macemu-${{ inputs.platform }}-${{ inputs.target_stage }}
          path: macemu-${{ inputs.platform }}-${{ inputs.target_stage }}.tar.gz
          
      # add to continuous release
      - uses: "ncipollo/release-action@v1"
        with:
          tag: "continuous"
          commit: "main"
          name: "Continuous release"
          prerelease: false
          draft: false
          bodyFile: .github/AUTORELEASE.md
          allowUpdates: true
          artifacts: "macemu-${{ inputs.platform }}-${{ inputs.target_stage }}.tar.gz"
          artifactContentType: application/gzip
