name: Compile amd64

inputs:
  platform:
    description: "Target platform, e.g. amd64 or i386"
    required: true
    default: "amd64"

# Controls when the workflow will run
on:
  workflow_dispatch: # Allows run manually from the Actions tab
  workflow_call: # Allow reuse of this workflow

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Compile
        run: sudo ./compile $INPUT_PLATFORM
      
      - name: Make nice directory name
        run: mv output macemu
      
      - name: Create tar.gz
        run: tar -czvf build-result-$INPUT_PLATFORM.tar.gz macemu
      
      # save artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: build-result-$INPUT_PLATFORM
          path: build-result-$INPUT_PLATFORM.tar.gz
