name: Compile and release
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # run this every month on the second monday at 7:20'o clock UTC
    #- cron:  '20 7 8-14 * 1'
    # run this every friday at 13:37 UTC
    - cron:  '37 13 * * 5'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # trigger workflows
  basilisk2_amd64:
    name: "BasiliskII amd64"
    uses: "./.github/workflows/BasiliskII amd64.yml"
  basilisk2_i386:
    name: "BasiliskII i386"
    uses: "./.github/workflows/BasiliskII i386.yml"
  sheepshaver_amd64:
    name: "SheepShaver amd64"
    uses: "./.github/workflows/SheepShaver amd64.yml"
  sheepshaver_i386:
    name: "SheepShaver i386"
    uses: "./.github/workflows/SheepShaver i386.yml"
