name: Delete tag
on:
  workflow_dispatch:
    inputs:
      tagname:
        type: string
        description: Tag name to delete
        required: true

jobs:
  delete_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Delete tag
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/${{ github.event.inputs.tagname }}"
            })
