name: Manual compile platform
on:
  workflow_dispatch: # Allows run manually from the Actions tab
    inputs:
      platform:
        description: "Target platform, e.g. x86_64 or i386"
        required: true
        default: "x86_64"
        type: string
      target_stage:
        description: "Target stage, e.g. combined or basilisk2 or sheepshaver"
        required: true
        default: "combined"
        type: string
jobs:
  compile:
    uses: ./.github/workflows/compile-platform.yml
    with:
      platform: ${{ github.event.inputs.platform }}
      target_stage: ${{ github.event.inputs.target_stage }}
      
