# This is a basic workflow to help you get started with Actions

name: Move tag continuous

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # run this every friday at 13:37 UTC
    - cron:  '37 13 * * 5'
jobs:
  move_it:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        
      - name: Move continuous tag
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}          
          script: |
            try {
                await github.rest.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: "tags/continuous"
                })
            } catch (e) {
              console.log("Tag 'continuous' does not exist yet? Error: " + e)
            }
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/continuous",
              sha: context.sha
            })

      # add to continuous release
      - uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd
        with:
          tag: "continuous"
          name: "Continuous release"
          prerelease: false
          draft: false
          bodyFile: .github/AUTORELEASE.md
          allowUpdates: true
