name: nothing

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/compile-platform.yml
        with:
          platform: amd64
          target_stage: nothing
      - uses: ./.github/workflows/update-continuous-release.yml
        with:
          platform: amd64
          target_stage: nothing
          workflow_file: nothing.yml

