name: Nothing

# test workflow performing a placebo build

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile-and-release:
    uses: ./.github/workflows/compile-platform.yml
    with:
      platform: x86_64
      target_stage: nothing
    
