name: Snapshot continuous release
on:
  workflow_dispatch:
    inputs:
      new_release_name:
        description: Name of the new release
        required: true
        type: string
jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # download continuous release assets
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: 'tags/continuous'
          file: 'macemu-amd64-basilisk2.AppImage'
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: 'tags/continuous'
          file: 'macemu-amd64-sheepshaver.AppImage'
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: 'tags/continuous'
          file: 'macemu-i386-basilisk2.AppImage'
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: 'tags/continuous'
          file: 'macemu-i386-sheepshaver.AppImage'
      
      # add to snapshot release
      - uses: "ncipollo/release-action@v1"
        with:
          tag: ${{ github.event.inputs.new_release_name }}
          name: ${{ github.event.inputs.new_release_name }}
          prerelease: false
          draft: true
          bodyFile: .github/AUTORELEASE.md
          allowUpdates: true
          artifacts: "*.AppImage"
