name: Snapshot continuous release
on:
  schedule:
    # run this every month on the second monday at 7:20'o clock UTC
    - cron:  '20 7 8-14 * 1'
  workflow_dispatch:
    inputs:
      new_release_name:
        description: Name of the new release
        required: false
        type: string
jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set ENV vars
        run: |
          NEW_RELEASE_NAME=${{ github.event.inputs.new_release_name }}
          echo "NEW_RELEASE_NAME=${NEW_RELEASE_NAME:-$(date +%Y-%m-%d)}" >> $GITHUB_ENV
        
        # download continuous release assets
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: 'tags/continuous'
          file: 'macemu-amd64-basilisk2.AppImage'
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: 'tags/continuous'
          file: 'macemu-amd64-sheepshaver.AppImage'
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: 'tags/continuous'
          file: 'macemu-i386-basilisk2.AppImage'
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: 'tags/continuous'
          file: 'macemu-i386-sheepshaver.AppImage'
      
      # add to snapshot release
      - uses: "ncipollo/release-action@v1"
        with:
          tag: ${{ env.NEW_RELEASE_NAME }}
          name: ${{ env.NEW_RELEASE_NAME }}
          prerelease: false
          draft: false
          bodyFile: .github/SNAPSHOTRELEASE.md
          allowUpdates: true
          artifacts: "*.AppImage"
