# This is a basic workflow to help you get started with Actions

name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- uses: dsaltares/fetch-gh-release-asset@master
      #  with:
      #    repo: ${{ github.repository }}
      #    version: 'tags/continuous'
      #    file: 'macemu-amd64-sheepshaver.tar.gz'
      
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          custom_tag: "test"
          
          
