# This is a basic workflow to help you get started with Actions

name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: 'tags/continuous'
          file: 'macemu-amd64-sheepshaver.tar.gz'
      
      - run: tar -xzf 'macemu-amd64-sheepshaver.tar.gz'
      
      
      
      # add AppImage direct downloads
      - name: Rename SheepShaver.AppImage for platform (if present)
        if: hashFiles('macemu/macemuAppImages/SheepShaver.AppImage') != ''
        run: mv macemu/macemuAppImages/SheepShaver.AppImage macemu-${{ inputs.platform }}-sheepshaver.AppImage
        
      - name: Rename BasiliskII.AppImage for platform (if present)
        if: hashFiles('macemu/macemuAppImages/BasiliskII.AppImage') != ''
        run: mv macemu/macemuAppImages/BasiliskII.AppImage macemu-${{ inputs.platform }}-basilisk2.AppImage
      
      - name: Upload SheepShaver AppImage direct asset to continuous release (if present)
        if: hashFiles('macemu-${{ inputs.platform }}-sheepshaver.AppImage') != ''
        uses: "ncipollo/release-action@v1"
        with:
          tag: "continuous"
          name: "Continuous release"
          prerelease: false
          draft: false
          allowUpdates: true
          artifacts: "macemu-${{ inputs.platform }}-sheepshaver.AppImage"
          artifactContentType: application/vnd.appimage
          
      - name: Upload BasiliskII AppImage direct asset to continuous release (if present)
        if: hashFiles('macemu-${{ inputs.platform }}-basilisk2.AppImage') != ''
        uses: "ncipollo/release-action@v1"
        with:
          tag: "continuous"
          name: "Continuous release"
          prerelease: false
          draft: false
          allowUpdates: true
          artifacts: "macemu-${{ inputs.platform }}-basilisk2.AppImage"
          artifactContentType: application/vnd.appimage
          
