# This is a basic workflow to help you get started with Actions

name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: github.repository
          version: 'tags/continuous'
          file: 'macemu-amd64-sheepshaver.tar.gz'
      
      - run: tar -xzf 'macemu-amd64-sheepshaver.tar.gz'
      - run: mv macemu/macemuAppImages/SheepShaver.AppImage macemu-amd64-sheepshaver.AppImage
      
      - uses: "ncipollo/release-action@v1"
        with:
          tag: "continuous"
          name: "Continuous release"
          prerelease: false
          draft: false
          bodyFile: .github/AUTORELEASE.md
          allowUpdates: true
          artifacts: "macemu-amd64-sheepshaver.AppImage"
          artifactContentType: application/vnd.appimage
          
